### ISSUE TITLE
Known macOS build issues with Protobuf version 3.19 and 3.20

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#1936]
When upgrading protobuf from 3.18.3 to 3.20.3, I noticed the macOS build failed with the following:

```
Undefined symbols for architecture x86_64:
[720](https://github.com/onnx/onnx-mlir/actions/runs/3743651637/jobs/6356066681#step:10:721)
  "google::protobuf::internal::InternalMetadata::~InternalMetadata()", referenced from:
[721](https://github.com/onnx/onnx-mlir/actions/runs/3743651637/jobs/6356066681#step:10:722)
      google::protobuf::MessageLite::~MessageLite() in libonnx_proto.a(onnx-ml.pb.cc.o)
[722](https://github.com/onnx/onnx-mlir/actions/runs/3743651637/jobs/6356066681#step:10:723)
      google::protobuf::MessageLite::~MessageLite() in libonnx_proto.a(onnx-data.pb.cc.o)
[723](https://github.com/onnx/onnx-mlir/actions/runs/3743651637/jobs/6356066681#step:10:724)
ld: symbol(s) not found for architecture x86_64
```

This is actually a known issue in the protobuf community, please see the following issues: 
https://github.com/protocolbuffers/protobuf/issues/9947
https://github.com/facebookincubator/velox/issues/2029
 
 
This problem is fixed in protobuf version 3.21.3, however `onnx` community has not upgraded to that version. Instead they are on version 3.20.3 which is where the failure lies. There is a workaround if we still want to upgrade to version 3.20.3 by adding the following to the CMake.txt file:

`add_definitions(-DNDEBUG)`

**Comment by hamptonm1** [comment]
Should we upgrade to protobuf 3.20.3 and include the workaround or should we wait for `onnx` to upgrade to `3.21.3` which fixes the issue and therefore we do not need to upgrade. @AlexandreEichenberger @gongsu832 @chentong319 @tungld ? Any comments about this topic :)

**Comment by gongsu832** [comment]
In general, only upgrade when there is a specific reason to do so. Stay in sync with onnx is desirable but if the new version has known problem like the one above, I'd wait until things get sorted out.

**Comment by chentong319** [comment]
To my understanding, protobuf 3.20.3 is required by onnx opset 18. protobuf 3.21 is needed for Mac to fix the issue with protobuf 3.20.3 on Mac. Can protobuf 3.21.3 work with other components in onnx-mlir? Open a draft PR to try?

**Comment by hamptonm1** [comment]
> To my understanding, protobuf 3.20.3 is required by onnx opset 18. protobuf 3.21 is needed for Mac to fix the issue with protobuf 3.20.3 on Mac. Can protobuf 3.21.3 work with other components in onnx-mlir? Open a draft PR to try?

So the `onnx` community upgraded to 3.20.2 because 3.18.3 is out of maintenance window as shown in the following PR : https://github.com/onnx/onnx/pull/4629. So it is not required to use opset 18 from what I read. I can create a draft PR and test what happens while using protobuf 3.21. Then everyone can decide based on my results.

**Comment by chentong319** [comment]
Thanks for your efforts. Your draft PR ran through on Mac, AMD and PPC Linux, but failed on S390 and Windows. It seems that Protobuf 3.20.2 is not available for Windows and can not be built on S390.

**Comment by hamptonm1** [comment]
> Thanks for your efforts. Your draft PR ran through on Mac, AMD and PPC Linux, but failed on S390 and Windows. It seems that Protobuf 3.20.2 is not available for Windows and can not be built on S390.

@chentong319 Yes I tested Protobuf 3.20.2, 3.20.3 and 3.21.3 which failed for some checks and not for others. So I guess we will have to remain at the version we are currently on.

**Comment by chentong319** [comment]
Yes, remain at the version we are currently on. Is it possible to use a different version for Mac only? Even if the git build for Mac fails for a while due to the Protobuf 3.18, I am building onnx-mlir locally on my Mac using Protobuf 3.20.3.

**Comment by hamptonm1** [comment]
> Yes, remain at the version we are currently on. Is it possible to use a different version for Mac only? Even if the git build for Mac fails for a while due to the Protobuf 3.18, I am building onnx-mlir locally on my Mac using Protobuf 3.20.3.

Interesting!! Okay let me try that.
